name: self-test-action

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  edge:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Send normal email
        uses: studioirf/send-email-notification@main
        with:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          subject: self-test-1 | ${{ github.repository }}:${{ github.ref_name }}-${{ github.run_id }}
          from-email: ${{ secrets.SENDGRID_FROM_EMAIL }}
          to-email: ${{ secrets.SENDGRID_TO_EMAIL }}
          markdown-body: |
            # Hello World

            This is a test email from self-test-action

      - name: Send email with attachments
        uses: studioirf/send-email-notification@main
        with:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          subject: self-test-2 | ${{ github.repository }}:${{ github.ref_name }}-${{ github.run_id }}
          from-email: ${{ secrets.SENDGRID_FROM_EMAIL }}
          to-email: ${{ secrets.SENDGRID_TO_EMAIL }}
          markdown-body: |
            # Hello again

            See attachment
          attachments: Attachments/test/*.txt
          
  stable:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Send normal email
        uses: studioirf/send-email-notification@v1
        with:
          api-key: ${{ secrets.SENDGRID_API_KEY }}
          subject: self-test-1 | ${{ github.repository }}:${{ github.ref_name }}-${{ github.run_id }}
          from-email: ${{ secrets.SENDGRID_FROM_EMAIL }}
          to-email: ${{ secrets.SENDGRID_TO_EMAIL }}
          markdown-body: ${{ github.event.release.body }}
